# instruction_induction.yaml
generation:
  num_subsamples: 2
  num_demos: 5
  num_prompts_per_subsample: 15
  model:
    name: GPT_forward
    batch_size: 300
    gpt_config:
      model: meta-llama/llama-3.3-70b-instruct:free # 修改这里
      api_base: https://openrouter.ai/api/v1
      temperature: 0.9
      max_tokens: 50
      top_p: 0.9
      frequency_penalty: 0.0
      presence_penalty: 0.0

evaluation:
  method: exec_accuracy
  num_samples: 15
  num_few_shot: 3
  model:
    name: GPT_forward
    batch_size: 15
    gpt_config:
      model: meta-llama/llama-3.3-70b-instruct:free  # 修改这里
      api_base: https://openrouter.ai/api/v1
      temperature: 0.7
      max_tokens: 100
      top_p: 1.0
      frequency_penalty: 0.0
      presence_penalty: 0.0

demo:
  model:
    name: GPT_forward
    batch_size: 300
    gpt_config:
      model: meta-llama/llama-3.3-70b-instruct:free  # 修改这里
      api_base: https://openrouter.ai/api/v1
      temperature: 0.7
      max_tokens: 100
      top_p: 1.0
      frequency_penalty: 0.0
      presence_penalty: 0.0
